# Generated by Django 5.0.3 on 2024-04-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(default='This is a comment', max_length=50),
        ),
    ]
